-- create utilization tracker table
CREATE TABLE utilization (
	hie_id varchar,
	subscriber_id varchar REFERENCES cap_list (subscriber_id),
	admission_id varchar,
	admit_date date,
	discharge_date date,
	inp6mo numeric,
	ed6mo numeric,
	PRIMARY KEY (admission_id)
);

-- add comment to this table
COMMENT ON TABLE utilization IS 'Patient Utilizations';

-- add comments to the columns
COMMENT ON COLUMN utilization.hie_id IS 'HIE ID generated by CareEvolution';
COMMENT ON COLUMN utilization.subscriber_id IS 'ID generated by insurance company';
COMMENT ON COLUMN utilization.admission_id IS 'ID generated for hospital admission';
COMMENT ON COLUMN utilization.admit_date IS 'Date of hospital admission';
COMMENT ON COLUMN utilization.discharge_date IS 'Discharge date of hospital admission';
COMMENT ON COLUMN utilization.inp6mo IS 'Number of inpatient admissions in last six months';
COMMENT ON COLUMN utilization.ed6mo IS 'Number of emergency department admissions in last six months';