-- create special ops table
CREATE TABLE spec_ops (
	hie_id varchar,
	subscriber_id varchar REFERENCES cap_list (subscriber_id),
	operations char,
	spec_ops_id varchar,
	PRIMARY KEY (spec_ops_id)
);

-- add comment to this table
COMMENT ON TABLE spec_ops IS 'Special Operations';

-- add comments to the columns
COMMENT ON COLUMN spec_ops.hie_id IS 'HIE ID generated by CareEvolution';
COMMENT ON COLUMN spec_ops.subscriber_id IS 'ID generated by insurance company';
COMMENT ON COLUMN spec_ops.operations IS 'Type of operations on the patients';
COMMENT ON COLUMN spec_ops.spec_ops_id IS 'Unique record number for special operations patients';
