-- create special ops table
CREATE TABLE spec_ops (
	subscriber_id varchar REFERENCES cap_list (subscriber_id),
	operations varchar,
	staff_assignment varchar,
	staff_assignment_other varchar,
	spec_ops_id varchar,
	PRIMARY KEY (spec_ops_id)
);

-- add comment to this table
COMMENT ON TABLE spec_ops IS 'Special Operations';

-- add comments to the columns
COMMENT ON COLUMN spec_ops.subscriber_id IS 'ID generated by insurance company';
COMMENT ON COLUMN spec_ops.operations IS 'Special operations ';
COMMENT ON COLUMN spec_ops.staff_assignment IS 'Staff member assigned to patient';
COMMENT ON COLUMN spec_ops.staff_assignment_other IS 'Additional staff member assigned to patient';
COMMENT ON COLUMN spec_ops.spec_ops_id IS 'Special ops ID, same as HIE ID';
