# Rename columns

# Set library
library(readr)
library(dplyr)

# Set working directory
setwd('Y:/database')

# Read in csv files
cap_list <- read_csv("cap_list.csv")
pra <- read_csv("pra.csv")
spec_ops <- read_csv("spec_ops.csv")
utilization <- read_csv("utilization.csv")
client_track <- read_csv("client_track.csv")

# Cap List
cap_list_rename <- rename(cap_list,
                   'hie_id' = `Patient ID HIE`,
                   'subscriber_id' = `SUBSCRIBER_ID`,
                   'unique_id' = `UniqueID`,
                   'practice' = `PRACTICE`,
                   'dob' = `DOB`,
                   'medicaid_no' = `MEDICAID_NO`,
                   'medicare_no' = `MEDICARE_NO`,
                   'memb_first_name' = `MEMB_FIRST_NAME`,
                   'memb_last_name' = `MEMB_LAST_NAME`,
                   'memb_add_1' = `MEMB_ADDRESS_LINE_1`,
                   'memb_add_2' = `MEMB_ADDRESS_LINE_2`,
                   'memb_city' = `MEMB_CITY`,
                   'memb_st' = `MEMB_STATE`,
                   'memb_zip' = `MEMB_ZIP`,
                   'memb_add' = `MEMB_ADDRESS`,
                   'ssn' = `SOCIAL_SEC_NO`,
                   'gender' = `GENDER`,
                   'memb_eth' = `MEMB_ETHNICITY`,
                   'memb_lang' = `MEMB_LANGUAGE`,
                   'home_phone' = `HOME_PHONE_NUMBER`,
                   'bus_phone' = `BUS_PHONE_NUMBER`,
                   'curr_pcp_id' = `CURR_PCP_ID`,
                   'curr_pcp_full_name' = `CURR_PCP_FULL_NAME`,
                   'phone_number' = `PHONE_NUMBER`,
                   'curr_pcp_address_line_1' = `CURR_PCP_ADDRESS_LINE_1`,
                   'curr_pcp_address_line_2' = `CURR_PCP_ADDRESS_LINE_2`,
                   'curr_pcp_city' = `CURR_PCP_CITY`,
                   'curr_pcp_st' = `CURR_PCP_STATE`,
                   'curr_pcp_zip' = `CURR_PCP_ZIP`,
                   'pcp_add' = `PCP_ADDRESS`,
                   'vend_id' = `VENDOR_ID`,
                   'vend_full_name' = `VEND_FULL_NAME`,
                   'irs_tax_id' = `IRS_TAX_ID`,
                   'memb_dim_id' = `MEMB_DIM_ID`,
                   'future_risk_costs' = `Future_Risk_Costs`,
                   'future_costs' = `Future_Costs`,
                   'prior_total_costs_annual' = `Prior_Total_Costs_Annualized`,
                   'prior_rx_costs_annual' = `Prior_Rx_Costs_Annualized`,
                   'future_rx_costs' = `Future_Rx_Costs`,
                   'memb_months' = `Member_Months`,
                   'memb_months_total' = `Total_Mem_Months`,
                   'last_cap_date' = `LastCapitationDate`,
                   'prim_risk_factor' = `Primary_Risk_Factor`,
                   'prev_cap_date ' = `Previous Capitation Date`,
                   'create_date' = `ArchiveCreatedDate`,
                   'high_risk_cohort' = `PAYER`,
                   'payer' = `Source`,
                   'source' = `HighRiskCohort`,
                   'xover_prog' = `Cross Over Program`,
                   'xover_prog_other' = `Cross Over Program Other`,
                   'span_speaking' = `SpanishSpeaking`,
                   'homeless' = `Currently Homeless`,
                   'notes_archive' = `AllnotesArchive`)

write_csv(cap_list_rename, path = "cap_list.csv")

# PRA Rename
pra_list_rename <- rename(pra,
                         'subscriber_id' = `SUBSCRIBER_ID_LINK2`,
                         'pra_id' = `PRAID`,
                         'pra_pat_id' = `PRA PATID`,
                         'engage' = `Engage`,
                         'pra_create_date' = `PRA Creation Date`,
                         'most_recent_update' = `Most Recent Update Date`,
                         'pra_fac_created' = `PRA Facility Created`,
                         'pra_fac_updated' = `PRA Facility Updated`,
                         'lmpdt' = `LMPDT`,
                         'edcdt' = `EDCDT`,
                         'est_preg_term' = `Estimated Preg Termination`,
                         'pra_risk_factor' = `PRA Risk Factor Details`,
                         'delivered_date' = `DeliveredDate`,
                         'delivery_details' = `DeliveryDetails`,
                         'delivery_details_other' = `Other Delivery Outcomes`,
                         'gest_diabetes' = `Gestational Diabetes`,
                         'preeclampsia' = `Preeclampsia`,
                         'delivery_details_risk_factors' = `Delivery details and risk factors`,
                         'workflow_closed_date' = `Workflow Closed Date`,
                         'workflow_closed_reason' = `Workflow Closed Reason`,
                         'preg_status' = `Pregnancy Status`,
                         'partner_prog' = `Partner Program`,
                         'partner_prog_other' = `Partner Program Other`,
                         'pra_risk_factor_yes_no' = `PRA Risk Factor`,
                         'risk_changed' = `RiskChangeDuringPregnancy`,
                         'comm_health_referral' = `Referred to CI/CHW/CHV`,
                         'add_services_pt_interest' = `Additional Services Patient Interest`,
                         'add_services_cchp_referral' = `Additional Services CCHP Referral`,
                         'risk_change_delivery' = `Delivery Risk Change`,
                         'pcp_risk_notification' = `PCP Risk Notification`,
                         'services_post_delivery_add' = `Additional Services Post Delivery`,
                         'hie_id' = `HIEID`)

write_csv(pra_list_rename, path = "pra.csv")

# Special Ops
spec_ops_rename <- rename(spec_ops, 
                          'subscriber_id' = `Subscriber_ID`,
                          'operations' = `Operations`,
                          'staff_assignment' = `Assigned To`,
                          'staff_assignment_other' = `Additional Staff`,
                          'spec_ops_id' = `Special Ops ID`)

write_csv(spec_ops_rename, path = "spec_ops.csv")

# Utilizations
ut_rename <- rename(utilization,
                    'subscriber_id' = `SUBSCRIBER_ID_LINK2`,
                    'admission_id' = `AdmissionID`,
                    'admit_date' = `AdmitDate`,
                    'discharge_date' = `DischargeDate`,
                    'provider' = `Provider`,
                    'current_admit' = `CurrentlyAdmitted`,
                    'facility' = `Facility`,
                    'patient_class' = `PatientClass`,
                    'dx_currentdx' = `CurrentDx`,
                    'dx_historical' = `HistoricalDiagnosis`,
                    'inp6mo' = `Inp6mo`,
                    'inp6mo_util' = `IP6mosatutilization`,
                    'ed6mo' = `ED6mo`,
                    'ed6mo_util' = `ED6mosatutilization`,
                    'chart_review_notes' = `ChartReviewNotes`,
                    'typology' = `Typology`,
                    'engage' = `Engage`,
                    'rule_out_reason' = `RuleOutReason`,
                    'rule_out_reason_other' = `OtherRuleOutReason`,
                    'call_assigned_to' = `CallAssignedTo`,
                    'bedside_assigned_to' = `BedsideAssignedTo`,
                    'workflow_complete_date' = `WorkflowCompleteDate`,
                    'engage_date' = `EngageDate`,
                    'bedside_not_possible_reason' = `ReasonBedsideNotPossible`,
                    'phone_current' = `CurrentPhone`,
                    'facility_description' = `Description of Facility`,
                    'deceased_date' = `PatientDeceasedDate`,
                    'appt_sched_date' = `Appt. Scheduled Date (PCP Input)`,
                    'appt_status' = `Appt. Status (PCP Input)`,
                    'gift_card_eligible_exception' = `Gift Card Eligible - Exception`,
                    'notes' = `Notes`,
                    'acr' = `ACR`,
                    'assigned_to' = `AssignedTo`,
                    'util_practice' = `PracticeAtUtilization`,
                    'util_source' = `SourceAtUtilization`,
                    'util_outcome' = `Utilization Outcome`,
                    'call_assigned_cchp' = `CallAssignedToCCHP`,
                    'taxi' = `Taxi`,
                    'taxi_sched' = `TaxiScheduled`,
                    'taxi_time' = `TaxiTime`,
                    'name_incorrect' = `Incorrect name`,
                    'name_correct' = `Correct Name`,
                    'name_error_reason' = `Name Error Reason`,
                    'bedside_assign_date' = `BedsideAssignmentDate`,
                    'hosp_room' = `Hospital Room`,
                    'util_outcome_other' = `Utilization Outcome Other`,
                    'util_outcome_cat' = `Utilization Outcome Category`,
                    'bed_engage_outcome' = `Bedside Engagement Outcome`,
                    'bed_engage_outcome_reason' = `Bedside Engagement Outcome Reason`,
                    'bed_engage_outcome_reason_other' = `Bedside Engagement Outcome Other Reason`,
                    'hie_error_desc' = `HIE Error Description`,
                    'hie_error_status' = `HIE Error Status`,
                    'hie_res_date' = `HIE Resolution Date`,
                    'hie_res_note' = `HIE Resolution Note`,
                    'preg_risk_factors' = `Pregnancy Risk Factors`,
                    'dx_cat_1' = `Diagnosis Category 1`,
                    'dx_cat_2' = `Diagnosis Category 2`,
                    'dx_cat_3' = `Diagnosis Category Other`,
                    'chief_complaint_1' = `Chief Complaint Category 1`,
                    'chief_complaint_2' = `Chief Complaint Category 2`,
                    'chief_complaint_3' = `Chief Complaint Category Other`)

write_csv(ut_rename, path = "utilization.csv")

# Client Track
ct_rename <- rename(client_track,
                    'admission_id' = `AdmissionID`,
                    'encounter' = `Encounter Type`,
                    'encounter_other' = `Other Type of Patient Encounter`,
                    'sched_date' = `Scheduled Date`,
                    'staff_assignment' = `Assigned To`,
                    'staff_assignment_other' = `Additional Staff Member`,
                    'sched_time' = `ScheduledTime`,
                    'encounter_date' = `EncounterDate`,
                    'ct_present' = `ClientPresent`,
                    'call_not_complete_reason' = `ReasonCallNotCompleted`,
                    'call_not_complete_reason_other' = `OtherReasonNoCall`,
                    'activities_completed' = `Activities Completed`,
                    'care_coord_method' = `Care Coordination Method`,
                    'care_coord_method_other' = `OtherCoordinationMethod`,
                    'hours' = `Hours`,
                    'documentation_hours' = `Documentation Hours`,
                    'notes' = `Notes`,
                    'home_visit_1_sched_complete_date' = `DateHomeVisit1SchedulingComplete`,
                    'home_visit_2_sched_complete_date' = `DateHomeVisit2SchedulingComplete`,
                    'gift_card_number' = `Gift Card Number`,
                    'gift_card_date' = `GiftCardDate`,
                    'gift_card_no' = `NoGiftCard`,
                    'dsr_service_activity' = `DSR Service Activity`,
                    'active_pt' = `Active Patient`,
                    'provider' = `Provider`,
                    'provider_other' = `Other Provider`,
                    'need_pcp_follow_up' = `Need PCP Follow Up`,
                    'need_care_coord_pcp' = `Need Care Coord at PCP`,
                    'follow_up_notes' = `Follow Up Notes`,
                    'pcp_12_mos' = `PCP in 12 Mos`,
                    'pcp_before_hosp' = `PCP Before Hospital`,
                    'action' = `Action`,
                    'action_other' = `Other Action`,
                    'no_action_reason' = `Reason No Action`,
                    'no_action_reason_other' = `Other Reason No Action`,
                    'hie_id' = `HIE ID Lookup`,
                    'duplicate' = `Duplicate`,
                    'init_practice_pcp_sched' = `PracticeAtInitialPCPScheduling`,
                    'init_practice_pcp_sched_other' = `PracticeAtInitialPCPSchedulingOther`,
                    'pra_id' = `PRAID`,
                    'ppv' = `PPV`,
                    'spec_ops_id' = `Special Ops Link`)

write_csv(ct_rename, path = "client_track.csv")

